'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawn,spawnSync}=require('node:child_process');
const doctorPath=path.resolve(__dirname,'../scripts/doctor.cjs');const api=fs.existsSync(doctorPath)?require(doctorPath):{};const baseline=require('../scripts/validate-baseline.cjs');
const probe=opts=>{assert.equal(typeof api.runProbe,'function','bounded doctor runner must exist');return api.runProbe({id:'fixture',executable:process.execPath,args:['--version'],timeoutMs:300,maxBytes:1024,...opts});};
test('doctor WDK accepts same-version x86 Inf2Cat and versioned IddCx without forging missing tools',t=>{
 assert.equal(typeof api.sdkMetadata,'function','component detector must support isolated WDK fixture');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'aether wdk fixture '));t.after(()=>{assert.equal(path.dirname(path.resolve(dir)),fs.realpathSync(os.tmpdir()));fs.rmSync(dir,{recursive:true,force:true});});
 const version='10.0.28000.0',files=[`Include/${version}/km/wdm.h`,`Include/${version}/um/iddcx/1.11/IddCx.h`,`Lib/${version}/km/x64/ntoskrnl.lib`,`bin/${version}/x64/stampinf.exe`,`bin/${version}/x86/Inf2Cat.exe`];for(const f of files){const p=path.join(dir,f);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,'component fixture only');}
 let r=api.sdkMetadata('windows-wdk',{root:dir});assert.equal(r.available,true);assert.equal(r.version,version);assert.equal(r.toolArchitectures.inf2cat,'x86');assert.equal(r.components.tools,true);
 fs.unlinkSync(path.join(dir,files.at(-1)));r=api.sdkMetadata('windows-wdk',{root:dir});assert.equal(r.available,false);assert.equal(r.components.tools,false);fs.mkdirSync(path.join(dir,'bin','10.0.26100.0','x86'),{recursive:true});fs.writeFileSync(path.join(dir,'bin','10.0.26100.0','x86','Inf2Cat.exe'),'wrong version');assert.equal(api.sdkMetadata('windows-wdk',{root:dir}).available,false);
});
test('doctor runner real Node version reaches normalized report',async()=>{const r=await probe({});assert.equal(r.status,'available');assert.match(r.version,/\d+\.\d+/);assert.equal(r.exitCode,0);assert.ok(r.durationMs>=0);});
test('doctor runner missing executable is missing, not available',async()=>{const r=await probe({executable:path.join(os.tmpdir(),'absent-aether-executable.exe')});assert.equal(r.status,'missing');assert.equal(r.version,null);});
test('doctor runner nonzero, empty and shim failure are distinct',async()=>{for(const [args,status]of[[['-e','process.exit(3)'],'failed'],[['-e',''],'empty']]){const r=await probe({args});assert.equal(r.status,status);assert.equal(r.version,null);}const r=await probe({runner:async()=>({error:{code:'EACCES',message:'shim unavailable'},exitCode:null,stdout:'',stderr:''})});assert.equal(r.status,'failed');});
test('doctor runner timeout cancels only its own process tree',async t=>{
 const other=spawn(process.execPath,['-e','setInterval(()=>{},1000)'],{windowsHide:true,stdio:'ignore'});t.after(()=>other.kill());
 const r=await probe({args:['-e','console.log(process.pid);setInterval(()=>{},1000)'],timeoutMs:300});assert.equal(r.status,'timeout');assert.ok(r.durationMs<2500);const pid=Number(r.stdout.trim());assert.ok(pid>0);assert.throws(()=>process.kill(pid,0),{code:'ESRCH'});assert.equal(other.exitCode,null);assert.equal(other.killed,false);
});
test('doctor runner bounded output, credentials and user path are redacted',async()=>{
 const secret='sk-proj-fixtureSecret0123456789';const r=await probe({args:['-e',`console.log('token=${secret}');console.log('password=hunterFixture');console.log(process.env.USERPROFILE||'');console.log('x'.repeat(6000))`],maxBytes:512});assert.equal(r.truncated,true);assert.ok(r.redactions>0);assert.ok(!JSON.stringify(r).includes(secret));assert.ok(!JSON.stringify(r).includes('hunterFixture'));if(process.env.USERPROFILE)assert.ok(!JSON.stringify(r).includes(process.env.USERPROFILE));
});
test('doctor runner shell characters never execute; batch arguments fail closed',async()=>{
 const r=await probe({executable:'cmd.exe & echo injected'});assert.equal(r.status,'failed');assert.ok(!r.stdout.includes('injected'));
 const b=await probe({id:'cmake',executable:'C:\\fixture\\cmake.cmd',args:['--version & echo injected']});assert.equal(b.status,'failed');assert.ok(!b.stdout.includes('injected'));
});
test('doctor runner known batch wrapper preserves spaces with fixed version flags',async t=>{
 if(process.platform!=='win32')return;
 assert.equal(typeof api.runProbe,'function');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'aether doctor spaces '));t.after(()=>{assert.equal(path.dirname(path.resolve(dir)),fs.realpathSync(os.tmpdir()));fs.rmSync(dir,{recursive:true,force:true});});const p=path.join(dir,'cmake.cmd');fs.writeFileSync(p,'@echo off\r\necho cmake version 4.0.0\r\n');const r=await probe({id:'cmake',executable:p,args:['--version'],timeoutMs:1000});assert.equal(r.status,'available',r.error);assert.match(r.launcher,/cmd.exe$/i);
});
test('doctor runner collection budget leaves late probes not-probed',async()=>{
 assert.equal(typeof api.collectEnvironment,'function');let time=0;const d=await api.collectEnvironment({mode:'Quick',clock:()=>time,probeSpecs:[{id:'one',executable:process.execPath,args:['--version']},{id:'two',executable:process.execPath,args:['--version']}],runner:async()=>{time+=26000;return {exitCode:0,stdout:'v24.14.0',stderr:''};},resolver:x=>x});assert.equal(d.probes[0].status,'available');assert.equal(d.probes[1].status,'not-probed');assert.equal(d.mode,'Quick');
});
// Plan 03 Task2: pure environment/method gates, prewritten with runner tests.
const envFixture=()=>{assert.equal(typeof baseline.validateEnvironment,'function','environment validator must exist');const platforms=['helios-windows10','helios-windows11','selene-windows','selene-macos','selene-ios-ipados','selene-android','selene-linux'].map(id=>({id,framework:{version:'3.44.0',source:'https://docs.flutter.dev/reference/supported-platforms',capturedAt:'2026-10-07',os:'candidate',architectures:['x64']},nativeConstraints:['pending real backend validation'],minimum:{status:id.startsWith('helios')?'pending-prototype':'proposed',os:id,architectures:['x64'],evidence:['source snapshot']},buildEvidence:[],hardwareEvidence:[],hardwareTodoId:id==='selene-macos'?'VFY-02':id==='selene-ios-ipados'?'VFY-01':null,gapIds:['toolchain']}));return {schemaVersion:1,capturedAt:'2026-10-07',purpose:'fixture',mode:'Quick',host:{ProductName:'Windows 10',Caption:'Windows 11',CurrentBuild:'26100',diagnostics:['registry product name conflicts with independent caption']},probes:[{id:'node',resolvedExecutable:'<runtime>/node.exe',launcher:'<runtime>/node.exe',args:['--version'],status:'available',version:'24.14.0',exitCode:0,durationMs:5,stdout:'24.14.0',stderr:'',truncated:false,redactions:0,error:null,requiredByPhases:[1],evidenceType:'executed'}],platforms,machines:[{id:'local',role:'windows',os:'Windows 11',architecture:'x64',gpuVendor:'unconfirmed',gpuModel:'unconfirmed',driver:'unconfirmed',availability:'verified',evidence:['OS query'],requiredByPhases:[1]}],gaps:[{id:'toolchain',component:'SDK',purpose:'target build',evidence:['not measured'],status:'open',followupPhases:[2],resolutionNeeded:'verify toolchain'}],scenarios:[{id:'desktop',description:'1080p60 LAN'}],measurementContract:{metrics:{'network-rtt':'ms','decode-duration':'ms','glass-to-glass':'ms','overlay-estimate':'ms','frame-drop':'%','jitter':'ms',cpu:'%',gpu:'%',vram:'MiB',power:'W'},method:{warmupSeconds:30,windowSeconds:60,repeats:3},clockRequirement:'calibrated cross-host differences'},decisions:[{id:'scope',status:'pending',options:[{id:'retain'}],selected:null}],review:{status:'pending',confirmedBy:null,confirmedAt:null,decisions:[],retainedBlockers:[]}};};
test('environment permits honest unknowns but strict review rejects pending',()=>{const d=envFixture();assert.deepEqual(baseline.validateEnvironment({data:d}).errors,[]);assert.ok(baseline.validateEnvironment({data:d,requireReview:true}).errors.length);d.decisions[0]={...d.decisions[0],status:'selected',selected:'retain',confirmedBy:'user',confirmedAt:'2026-10-07T10:00:00Z'};d.review={status:'confirmed',confirmedBy:'user',confirmedAt:'2026-10-07T10:00:00Z',decisions:['scope'],retainedBlockers:['toolchain']};assert.deepEqual(baseline.validateEnvironment({data:d,requireReview:true}).errors,[]);});
for(const [name,mutate,match]of[
 ['header-only SDK',d=>d.probes.push({...d.probes[0],id:'windows-sdk',version:'10.0',evidenceType:'sdk-components',components:{headers:true,libs:false,tools:false}}),/SDK|component/],
 ['unreported OS conflict',d=>d.host.diagnostics=[],/conflict|diagnostic/],
 ['Apple fake hardware',d=>d.platforms.find(p=>p.id==='selene-macos').hardwareEvidence=[{kind:'build',status:'passed'}],/hardware|Apple/],
 ['Apple missing build gap',d=>{const p=d.platforms.find(p=>p.id==='selene-ios-ipados');p.gapIds=[];},/build|gap/],
 ['unapproved hardware TODO',d=>d.platforms[0].hardwareTodoId='VFY-01',/TODO/],
 ['raised Win10 floor',d=>d.platforms[0].minimum={...d.platforms[0].minimum,status:'confirmed',os:'Windows 11'},/Win10|prototype/],
 ['failed probe forged available',d=>d.probes[0].exitCode=5,/available|exit/],
 ['missing output diagnostic',d=>d.probes[0].status='unknown',/probe|status/]
])test(`environment rejects ${name}`,()=>{const d=envFixture();mutate(d);assert.match(baseline.validateEnvironment({data:d}).errors.join('\n'),match);});
const measurement=()=>({schemaVersion:1,scenarioId:'desktop',reference:{repo:'moonlight-qt',commit:'a'.repeat(40),binaryDigest:'sha256:'+'b'.repeat(64)},hostId:'h',clientId:'c',osGpuDriver:{host:'Win11/GPU/driver',client:'Win11/GPU/driver'},network:{type:'LAN',rttMs:2},resolution:{width:1920,height:1080},fps:60,codec:'h264',hdr:false,audio:'stereo',sampling:{warmupSeconds:30,windowSeconds:60,repeats:3,clockMethod:'single-clock',instrument:'fixture',accuracy:'1ms'},samples:[1,2,3,4,5].map(value=>({metric:'network-rtt',unit:'ms',value,timestamp:'2026-10-07T10:00:00Z',origin:'actual instrument'})),failures:[]});
test('measurement nearest-rank grouping and zero samples',()=>{assert.equal(typeof baseline.validateMeasurement,'function','measurement validator must exist');const d=measurement(),r=baseline.validateMeasurement(d);assert.deepEqual(r.errors,[]);assert.equal(r.summary['network-rtt/ms'].p50,3);assert.equal(r.summary['network-rtt/ms'].p95,5);d.samples=[];const empty=baseline.validateMeasurement(d);assert.equal(empty.status,'unavailable');assert.deepEqual(empty.summary,{});});
for(const [name,mutate,match]of[
 ['wrong metric unit',d=>d.samples[0].unit='W',/unit/],
 ['uncalibrated clocks',d=>{d.sampling.clockMethod='cross-machine';d.samples[0].origin='cross-machine timestamp difference';},/clock|calibrat/],
 ['missing binary digest',d=>delete d.reference.binaryDigest,/reference|digest/],
 ['fabricated negative value',d=>d.samples[0].value=-1,/value/]
])test(`measurement rejects ${name}`,()=>{assert.equal(typeof baseline.validateMeasurement,'function');const d=measurement();mutate(d);assert.match(baseline.validateMeasurement(d).errors.join('\n'),match);});
test('measurement comparison refuses mismatched parameters',()=>{assert.equal(typeof baseline.validateMeasurement,'function');const a=measurement(),b=measurement();b.codec='av1';assert.match(baseline.validateMeasurement(a,{compare:b}).errors.join('\n'),/comparab|parameter/);});
test('doctor runner JSON credentials and escaped user directories are redacted',async()=>{const r=await probe({runner:async()=>({exitCode:0,stdout:JSON.stringify({password:'jsonFixtureSecret',path:'C:\\Users\\FixtureAccount\\sdk'}),stderr:''})});assert.ok(!JSON.stringify(r).includes('jsonFixtureSecret'));assert.ok(!JSON.stringify(r).includes('FixtureAccount'));});
test('environment cached Flutter version cannot silently change historical floors',()=>{const d=envFixture();d.probes.push({...d.probes[0],id:'flutter-cache',version:'3.47.0'});assert.match(baseline.validateEnvironment({data:d}).errors.join('\n'),/Flutter|version/);});
test('measurement rejects missing record, bad percentages and unsupported clock',()=>{for(const d of [null,{...measurement(),samples:[{metric:'cpu',unit:'%',value:101,timestamp:'2026-10-07',origin:'counter'}]},{...measurement(),sampling:{...measurement().sampling,clockMethod:'unknown'}}])assert.ok(baseline.validateMeasurement(d).errors.length);});
test('environment and measurement CLI preserve failures, pending review and path guard',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'aether baseline cli '));t.after(()=>{assert.equal(path.dirname(path.resolve(dir)),fs.realpathSync(os.tmpdir()));fs.rmSync(dir,{recursive:true,force:true});});fs.mkdirSync(path.join(dir,'docs','baseline'),{recursive:true});const p=path.resolve(__dirname,'../scripts/validate-baseline.cjs');const run=args=>spawnSync(process.execPath,[p,'--root',dir,...args],{encoding:'utf8',windowsHide:true,timeout:5000});const d=envFixture(),envPath=path.join(dir,'docs','baseline','environment.json');fs.writeFileSync(envPath,JSON.stringify(d));assert.equal(run(['--environment']).status,0);const pending=run(['--review','--require-review']);assert.notEqual(pending.status,0);assert.match(pending.stderr,/review|pending/);d.decisions[0]={...d.decisions[0],status:'selected',selected:'retain',confirmedBy:'user',confirmedAt:'2026-10-07T10:00:00Z'};d.review={status:'confirmed',confirmedBy:'user',confirmedAt:'2026-10-07T10:00:00Z',decisions:['scope'],retainedBlockers:['toolchain']};fs.writeFileSync(envPath,JSON.stringify(d));assert.equal(run(['--environment','--require-review']).status,0);const m=measurement();fs.writeFileSync(path.join(dir,'measurement.json'),JSON.stringify(m));const valid=run(['--measurement','measurement.json']);assert.equal(valid.status,0,valid.stderr);assert.equal(JSON.parse(valid.stdout).summary['network-rtt/ms'].p95,5);const comparison=measurement();comparison.codec='av1';fs.writeFileSync(path.join(dir,'compare.json'),JSON.stringify(comparison));const mismatch=run(['--measurement','measurement.json','--compare','compare.json']);assert.notEqual(mismatch.status,0);assert.match(mismatch.stderr,/parameter/);m.samples=[];fs.writeFileSync(path.join(dir,'measurement.json'),JSON.stringify(m));assert.equal(JSON.parse(run(['--measurement','measurement.json']).stdout).measurementStatus,'unavailable');assert.notEqual(run(['--measurement','../outside.json']).status,0);m.samples=[{metric:'cpu',unit:'W',value:1}];fs.writeFileSync(path.join(dir,'measurement.json'),JSON.stringify(m));assert.notEqual(run(['--measurement','measurement.json']).status,0);});
