'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process');
const ROOT=path.resolve(__dirname,'..'),STATUSES=['available','missing','failed','timeout','empty','not-probed'];
const FIXED_BATCH={cmake:['--version'],ninja:['--version'],git:['--version'],java:['-version']};
function redact(value){let count=0,s=String(value??'');const replace=(re,replacement)=>{s=s.replace(re,()=>{count++;return replacement;});};
 replace(/sk-(?:proj-|svcacct-)?[A-Za-z0-9_-]{10,}/g,'<redacted-key>');replace(/\b(?:token|password|secret|api[_-]?key)\s*[=:]\s*[^\s'";]+/gi,'<redacted-credential>');replace(/Bearer\s+[^\s'";]+/gi,'Bearer <redacted>');
 for(const p of [process.env.USERPROFILE,process.env.HOME].filter(Boolean).sort((a,b)=>b.length-a.length)){replace(new RegExp(p.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'gi'),'<user>');}
 replace(/[A-Z]:[\\/]Users[\\/][^\\/\s'";]+/gi,'<user>');return {text:s,count};}
function resolveTool(name){if(path.isAbsolute(name))return fs.existsSync(name)?name:null;for(const dir of (process.env.PATH||'').split(path.delimiter)){if(!dir)continue;for(const suffix of process.platform==='win32'?['.exe','.cmd','.bat','']:['']){const p=path.resolve(dir,name+suffix);try{if(fs.statSync(p).isFile())return p;}catch{}}}return null;}
function launchSpec(id,executable,args){if(typeof executable!=='string'||!path.isAbsolute(executable)||/[&|<>^%!\r\n"]/.test(executable))throw Error('Executable must be an absolute validated path without shell metacharacters');
 if(!Array.isArray(args)||args.some(x=>typeof x!=='string'||/[\r\n]/.test(x)))throw Error('Invalid argument array');
 if(/\.(cmd|bat)$/i.test(executable)){const fixed=FIXED_BATCH[id];if(!fixed||JSON.stringify(args)!==JSON.stringify(fixed)||args.some(x=>/[&|<>^%!"\r\n]/.test(x)))throw Error('Batch launcher accepts only whitelisted fixed version arguments');const launcher=path.join(process.env.SystemRoot||'C:\\Windows','System32','cmd.exe');return {launcher,args:['/d','/s','/c',`""${executable}" ${fixed.join(' ')}"`],windowsVerbatimArguments:true};}
 if(/\.ps1$/i.test(executable)){const launcher=resolveTool('pwsh');if(!launcher)throw Error('PowerShell launcher missing');return {launcher,args:['-NoProfile','-File',executable,...args]};}
 return {launcher:executable,args};}
function nativeRunner({launcher,args,timeoutMs,maxBytes,windowsVerbatimArguments}){return new Promise(resolve=>{let child,done=false,timer,killTimer,stdout=Buffer.alloc(0),stderr=Buffer.alloc(0),truncated=false,timedOut=false,error=null;const start=Date.now();
 const finish=exitCode=>{if(done)return;done=true;clearTimeout(timer);clearTimeout(killTimer);resolve({exitCode,stdout:stdout.toString('utf8'),stderr:stderr.toString('utf8'),truncated,timeout:timedOut,error,durationMs:Date.now()-start});};
 const cancel=()=>{if(!child?.pid)return;if(process.platform==='win32'){const killer=cp.spawn(path.join(process.env.SystemRoot||'C:\\Windows','System32','taskkill.exe'),['/PID',String(child.pid),'/T','/F'],{windowsHide:true,stdio:'ignore'});killer.on('error',()=>child.kill());setTimeout(()=>{if(killer.exitCode===null){killer.kill();child.kill();}},1500).unref();}else child.kill('SIGKILL');killTimer=setTimeout(()=>{child.kill();child.stdout.destroy();child.stderr.destroy();finish(null);},2000);};
 try{child=cp.spawn(launcher,args,{windowsHide:true,windowsVerbatimArguments:!!windowsVerbatimArguments,shell:false,stdio:['ignore','pipe','pipe']});}catch(e){error={code:e.code,message:e.message};finish(null);return;}
 child.on('error',e=>{error={code:e.code,message:e.message};finish(null);});child.on('close',finish);
 for(const stream of ['stdout','stderr'])child[stream].on('data',b=>{let previous=stream==='stdout'?stdout:stderr;if(previous.length+b.length>maxBytes)truncated=true;previous=Buffer.concat([previous,b.subarray(0,Math.max(0,maxBytes-previous.length))]);if(stream==='stdout')stdout=previous;else stderr=previous;});
 timer=setTimeout(()=>{timedOut=true;cancel();},timeoutMs);
 });}
async function runProbe({id,executable,args=[],timeoutMs=5000,maxBytes=65536,runner=nativeRunner,requiredByPhases=[],evidenceType='executed'}){const start=Date.now();let spec,result;
 try{spec=launchSpec(id,executable,args);result=await runner({...spec,executable,id,timeoutMs:Math.max(1,Math.min(timeoutMs,5000)),maxBytes:Math.max(1,Math.min(maxBytes,65536))});}catch(e){result={error:{code:e.code,message:e.message},exitCode:null,stdout:'',stderr:''};}
 const fields={resolvedExecutable:executable||null,launcher:spec?.launcher||null,args,stdout:result.stdout||'',stderr:result.stderr||'',error:result.error?String(result.error.message||result.error):null};let redactions=0;for(const k of Object.keys(fields)){if(k==='args'){fields[k]=fields[k].map(a=>{const r=redact(a);redactions+=r.count;return r.text;});}else if(fields[k]!==null){const r=redact(fields[k]);redactions+=r.count;fields[k]=r.text;}}
 let status=result.timeout?'timeout':result.error?(result.error.code==='ENOENT'?'missing':'failed'):result.exitCode!==0?'failed':!(fields.stdout+fields.stderr).trim()?'empty':'available';
 const version=status==='available'?((fields.stdout+' '+fields.stderr).match(/(?<![0-9])v?(\d+(?:\.\d+){1,4}(?:[-+][\w.-]+)?)/)||[])[1]||null:null;
 return {id,...fields,status,version,exitCode:result.exitCode??null,durationMs:result.durationMs??Date.now()-start,truncated:!!result.truncated,redactions,requiredByPhases,evidenceType};}
function metadataProbe(id,data,requiredByPhases,evidenceType){const output=redact(JSON.stringify(data));return {id,resolvedExecutable:null,launcher:null,args:[],status:data.available?'available':'missing',version:data.available?data.version||null:null,exitCode:data.available?0:null,durationMs:0,stdout:output.text,stderr:'',truncated:false,redactions:output.count,error:data.available?null:data.reason||'No complete local evidence',requiredByPhases,evidenceType,...(data.components?{components:data.components}:{}),metadata:JSON.parse(output.text)};}
function sdkMetadata(kind){const root=path.join(process.env['ProgramFiles(x86)']||'C:\\Program Files (x86)','Windows Kits','10');let versions=[];try{versions=fs.readdirSync(path.join(root,'Include')).filter(v=>/^10\.0\.\d+\.0$/.test(v)).sort();}catch{}
 const candidates=versions.map(version=>{const include=path.join(root,'Include',version),lib=path.join(root,'Lib',version),bin=path.join(root,'bin',version,'x64');const components=kind==='windows-sdk'?{headers:fs.existsSync(path.join(include,'um','Windows.h'))&&fs.existsSync(path.join(include,'ucrt','stdio.h')),libs:fs.existsSync(path.join(lib,'um','x64','kernel32.lib'))&&fs.existsSync(path.join(lib,'ucrt','x64','ucrt.lib')),tools:fs.existsSync(path.join(bin,'rc.exe'))&&fs.existsSync(path.join(bin,'mt.exe'))}:{headers:fs.existsSync(path.join(include,'km','wdm.h'))&&fs.existsSync(path.join(include,'um','iddcx','1.0','IddCx.h')),libs:fs.existsSync(path.join(lib,'km','x64','ntoskrnl.lib')),tools:fs.existsSync(path.join(bin,'stampinf.exe'))&&fs.existsSync(path.join(bin,'Inf2Cat.exe'))};return {version,components,available:Object.values(components).every(Boolean)};});const complete=candidates.filter(v=>v.available).at(-1);return {available:!!complete,version:complete?.version||null,components:complete?.components||candidates.at(-1)?.components||{headers:false,libs:false,tools:false},candidates,reason:'No matching headers, libraries and tools verified together'};}
const OS_QUERY='$ErrorActionPreference="Stop"; $r=Get-ItemProperty -LiteralPath "HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion"; $o=Get-CimInstance Win32_OperatingSystem; $g=@(Get-CimInstance Win32_VideoController | Select-Object AdapterCompatibility,Name,DriverVersion); [ordered]@{ProductName=$r.ProductName;DisplayVersion=$r.DisplayVersion;CurrentBuild=$r.CurrentBuild;UBR=$r.UBR;Caption=$o.Caption;OSArchitecture=$o.OSArchitecture;ProcessArchitecture=[System.Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture.ToString();gpus=$g} | ConvertTo-Json -Depth 5 -Compress';
async function collectEnvironment({mode='Quick',runner,resolver=resolveTool,clock=Date.now,probeSpecs}={}){if(!['Quick','Deep'].includes(mode))throw Error('Mode must be Quick or Deep');const start=clock(),budgetMs=mode==='Quick'?25000:45000,probes=[];
 const vswhere=path.join(process.env['ProgramFiles(x86)']||'C:\\Program Files (x86)','Microsoft Visual Studio','Installer','vswhere.exe');
 const specs=probeSpecs||[{id:'node',executable:process.execPath,args:['--version'],requiredByPhases:[1,2]},{id:'git',tool:'git',args:['--version'],requiredByPhases:[1]},{id:'powershell',tool:'pwsh',args:['-NoProfile','-Command','$PSVersionTable.PSVersion.ToString()'],requiredByPhases:[1]},{id:'cmake',tool:'cmake',args:['--version'],requiredByPhases:[2]},{id:'ninja',tool:'ninja',args:['--version'],requiredByPhases:[2]},{id:'visual-cpp',executable:vswhere,args:['-all','-products','*','-requires','Microsoft.VisualStudio.Component.VC.Tools.x86.x64','-format','json'],requiredByPhases:[2,3,4,5]},{id:'java',tool:'java',args:['-version'],requiredByPhases:[2,14]},{id:'windows-host',tool:'pwsh',args:['-NoProfile','-Command',OS_QUERY],requiredByPhases:[1,3,4,5]}];
 for(const s of specs){const remaining=budgetMs-(clock()-start);if(remaining<=0){probes.push({id:s.id,resolvedExecutable:null,launcher:null,args:[],status:'not-probed',version:null,exitCode:null,durationMs:0,stdout:'',stderr:'',truncated:false,redactions:0,error:'Collection budget exhausted',requiredByPhases:s.requiredByPhases||[],evidenceType:'executed'});continue;}
 const executable=s.executable||resolver(s.tool);probes.push(executable?await runProbe({...s,executable,runner,timeoutMs:Math.min(5000,remaining)}):{id:s.id,resolvedExecutable:null,launcher:null,args:s.args,status:'missing',version:null,exitCode:null,durationMs:0,stdout:'',stderr:'',truncated:false,redactions:0,error:'Executable not resolved',requiredByPhases:s.requiredByPhases||[],evidenceType:'executed'});}
 let host={ProductName:null,DisplayVersion:null,CurrentBuild:null,UBR:null,Caption:null,OSArchitecture:process.arch,ProcessArchitecture:process.arch,diagnostics:[]};const osProbe=probes.find(p=>p.id==='windows-host');if(osProbe?.status==='available'){try{host={...host,...JSON.parse(osProbe.stdout)};}catch{host.diagnostics.push('Independent OS query output could not be parsed');}}else host.diagnostics.push('Independent OS query unavailable');
 if(host.ProductName&&host.Caption&&/Windows 10/.test(host.ProductName)&&/Windows 11/.test(host.Caption))host.diagnostics.push('Registry ProductName says Windows 10; independent CIM Caption says Windows 11. Preserve both; this is not a Win10 test machine.');
 if(!probeSpecs){probes.push(metadataProbe('windows-sdk',sdkMetadata('windows-sdk'),[2,3,4,5],'sdk-components'),metadataProbe('windows-wdk',sdkMetadata('windows-wdk'),[3,4],'sdk-components'));
 const flutterCommand=resolver('flutter'),flutterRoot=flutterCommand?path.dirname(path.dirname(flutterCommand)):null;let flutter={available:false,reason:'Flutter cached SDK metadata not found; wrapper not executed'};if(flutterRoot){try{const v=JSON.parse(fs.readFileSync(path.join(flutterRoot,'bin','cache','flutter.version.json'),'utf8'));const dart=path.join(flutterRoot,'bin','cache','dart-sdk','bin',process.platform==='win32'?'dart.exe':'dart');flutter={available:fs.existsSync(dart),version:v.flutterVersion,frameworkRevision:v.frameworkRevision,dartSdkVersion:v.dartSdkVersion,source:path.join(flutterRoot,'bin','cache','flutter.version.json'),reason:'Cached Dart executable absent'};}catch{}}
 probes.push(metadataProbe('flutter-cache',flutter,[2],'cached-metadata'));
 if(flutterRoot&&flutter.available&&budgetMs-(clock()-start)>0)probes.push(await runProbe({id:'dart',executable:path.join(flutterRoot,'bin','cache','dart-sdk','bin','dart.exe'),args:['--version'],runner,timeoutMs:Math.min(5000,budgetMs-(clock()-start)),requiredByPhases:[2]}));
 const androidRoot=process.env.ANDROID_SDK_ROOT||process.env.ANDROID_HOME||path.join(process.env.LOCALAPPDATA||'','Android','Sdk');let android={available:false,reason:'Android platform, build-tools and SDK tools not all verified'};try{const platforms=fs.readdirSync(path.join(androidRoot,'platforms')),buildTools=fs.readdirSync(path.join(androidRoot,'build-tools'));android={...android,available:platforms.length>0&&buildTools.length>0&&fs.existsSync(path.join(androidRoot,'platform-tools','adb.exe')),version:buildTools.sort().at(-1),platforms,buildTools};}catch{}probes.push(metadataProbe('android-sdk',android,[2,14],'sdk-components'));
 let ndk={available:false,reason:'Android NDK metadata not found'};try{const versions=fs.readdirSync(path.join(androidRoot,'ndk'));ndk={available:versions.length>0,version:versions.sort().at(-1),versions};}catch{}probes.push(metadataProbe('android-ndk',ndk,[2,14],'cached-metadata'));}
 return {schemaVersion:1,capturedAt:new Date().toISOString(),purpose:'Read-only local tool and machine observation; no product support or performance claim',mode,budget:{budgetMs,durationMs:clock()-start,perProbeMs:5000,maxBytesPerStream:65536},host,probes:probes.sort((a,b)=>a.id.localeCompare(b.id)),platforms:[],machines:[],gaps:[],scenarios:[],measurementContract:{},decisions:[],review:{status:'pending',confirmedBy:null,confirmedAt:null,decisions:[],retainedBlockers:[]}};}
async function cli(argv=process.argv.slice(2)){let mode='Quick',output='docs/baseline/environment.json';for(let i=0;i<argv.length;i++){if(argv[i]==='--mode')mode=argv[++i];else if(argv[i]==='--output')output=argv[++i];else throw Error('Unknown doctor argument');}if(output!=='docs/baseline/environment.json')throw Error('Output must be docs/baseline/environment.json');const data=await collectEnvironment({mode});const target=path.join(ROOT,output);if(fs.existsSync(target)){const old=JSON.parse(fs.readFileSync(target,'utf8'));if(old.review?.status==='confirmed')throw Error('Confirmed snapshot requires explicit review reset before replacement');for(const k of ['platforms','scenarios','measurementContract','decisions','review'])if(old[k]&&(Array.isArray(old[k])?old[k].length:Object.keys(old[k]).length))data[k]=old[k];}fs.mkdirSync(path.dirname(target),{recursive:true});const temp=target+'.tmp';fs.writeFileSync(temp,JSON.stringify(data,null,2)+'\n');fs.renameSync(temp,target);return {status:'PASS',mode,output,durationMs:data.budget.durationMs,budgetMs:data.budget.budgetMs,probes:data.probes.map(p=>({id:p.id,status:p.status,version:p.version})),productSupportVerified:false};}
module.exports={runProbe,collectEnvironment,redact,STATUSES,cli};if(require.main===module)cli().then(r=>console.log(JSON.stringify(r))).catch(e=>{console.error(JSON.stringify({status:'FAIL',error:redact(e.message).text}));process.exitCode=1;});
