// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

class AetherBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  AetherBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  AetherBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int aether_core_ack(int token, int sequence) {
    return _aether_core_ack(token, sequence);
  }

  late final _aether_core_ackPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Uint64, ffi.Uint64)>>(
        'aether_core_ack',
      );
  late final _aether_core_ack = _aether_core_ackPtr
      .asFunction<int Function(int, int)>();

  int aether_core_cancel(int token, int operation_id) {
    return _aether_core_cancel(token, operation_id);
  }

  late final _aether_core_cancelPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Uint64, ffi.Uint64)>>(
        'aether_core_cancel',
      );
  late final _aether_core_cancel = _aether_core_cancelPtr
      .asFunction<int Function(int, int)>();

  int aether_core_capabilities(
    int platform_id,
    ffi.Pointer<AetherCapabilities> out,
  ) {
    return _aether_core_capabilities(platform_id, out);
  }

  late final _aether_core_capabilitiesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Uint32, ffi.Pointer<AetherCapabilities>)
        >
      >('aether_core_capabilities');
  late final _aether_core_capabilities = _aether_core_capabilitiesPtr
      .asFunction<int Function(int, ffi.Pointer<AetherCapabilities>)>();

  int aether_core_create(
    ffi.Pointer<AetherConfig> config,
    AetherEventCallback callback,
    ffi.Pointer<ffi.Uint64> token,
  ) {
    return _aether_core_create(config, callback, token);
  }

  late final _aether_core_createPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<AetherConfig>,
            AetherEventCallback,
            ffi.Pointer<ffi.Uint64>,
          )
        >
      >('aether_core_create');
  late final _aether_core_create = _aether_core_createPtr
      .asFunction<
        int Function(
          ffi.Pointer<AetherConfig>,
          AetherEventCallback,
          ffi.Pointer<ffi.Uint64>,
        )
      >();

  int aether_core_destroy(int token) {
    return _aether_core_destroy(token);
  }

  late final _aether_core_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Uint64)>>(
        'aether_core_destroy',
      );
  late final _aether_core_destroy = _aether_core_destroyPtr
      .asFunction<int Function(int)>();

  int aether_core_start_probe(
    int token,
    int delay_ms,
    int flags,
    ffi.Pointer<ffi.Uint64> operation_id,
  ) {
    return _aether_core_start_probe(token, delay_ms, flags, operation_id);
  }

  late final _aether_core_start_probePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Uint64,
            ffi.Uint32,
            ffi.Uint32,
            ffi.Pointer<ffi.Uint64>,
          )
        >
      >('aether_core_start_probe');
  late final _aether_core_start_probe = _aether_core_start_probePtr
      .asFunction<int Function(int, int, int, ffi.Pointer<ffi.Uint64>)>();

  int aether_core_stats(int token, ffi.Pointer<AetherStats> out) {
    return _aether_core_stats(token, out);
  }

  late final _aether_core_statsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Uint64, ffi.Pointer<AetherStats>)
        >
      >('aether_core_stats');
  late final _aether_core_stats = _aether_core_statsPtr
      .asFunction<int Function(int, ffi.Pointer<AetherStats>)>();

  int aether_core_stop(int token, ffi.Pointer<ffi.Uint64> final_sequence) {
    return _aether_core_stop(token, final_sequence);
  }

  late final _aether_core_stopPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Uint64, ffi.Pointer<ffi.Uint64>)
        >
      >('aether_core_stop');
  late final _aether_core_stop = _aether_core_stopPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Uint64>)>();

  int aether_core_thread_id() {
    return _aether_core_thread_id();
  }

  late final _aether_core_thread_idPtr =
      _lookup<ffi.NativeFunction<ffi.Uint64 Function()>>(
        'aether_core_thread_id',
      );
  late final _aether_core_thread_id = _aether_core_thread_idPtr
      .asFunction<int Function()>();

  int aether_core_version(
    int abi_version,
    ffi.Pointer<ffi.Char> buffer,
    int capacity,
    ffi.Pointer<ffi.Uint32> required,
  ) {
    return _aether_core_version(abi_version, buffer, capacity, required);
  }

  late final _aether_core_versionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Uint32,
            ffi.Pointer<ffi.Char>,
            ffi.Uint32,
            ffi.Pointer<ffi.Uint32>,
          )
        >
      >('aether_core_version');
  late final _aether_core_version = _aether_core_versionPtr
      .asFunction<
        int Function(int, ffi.Pointer<ffi.Char>, int, ffi.Pointer<ffi.Uint32>)
      >();
}

final class AetherCapabilities extends ffi.Struct {
  @ffi.Uint32()
  external int abi_version;

  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int platform_id;

  @ffi.Uint32()
  external int interface_version;

  @ffi.Uint64()
  external int capability_bits;

  @ffi.Uint32()
  external int implemented;

  @ffi.Uint32()
  external int reason_code;

  static ffi.Pointer<AetherCapabilities> $allocate(
    ffi.Allocator $allocator, {
    required int abi_version,
    required int struct_size,
    required int platform_id,
    required int interface_version,
    required int capability_bits,
    required int implemented,
    required int reason_code,
  }) => $allocator<AetherCapabilities>()
    ..ref.abi_version = abi_version
    ..ref.struct_size = struct_size
    ..ref.platform_id = platform_id
    ..ref.interface_version = interface_version
    ..ref.capability_bits = capability_bits
    ..ref.implemented = implemented
    ..ref.reason_code = reason_code;
}

enum AetherCapability {
  AETHER_LOCAL_CORE(1),
  AETHER_PRESENTATION(2);

  final int value;
  const AetherCapability(this.value);

  static AetherCapability fromValue(int value) => switch (value) {
    1 => AETHER_LOCAL_CORE,
    2 => AETHER_PRESENTATION,
    _ => throw ArgumentError('Unknown value for AetherCapability: $value'),
  };
}

final class AetherConfig extends ffi.Struct {
  @ffi.Uint32()
  external int abi_version;

  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int flags;

  @ffi.Uint32()
  external int reserved;

  static ffi.Pointer<AetherConfig> $allocate(
    ffi.Allocator $allocator, {
    required int abi_version,
    required int struct_size,
    required int flags,
    required int reserved,
  }) => $allocator<AetherConfig>()
    ..ref.abi_version = abi_version
    ..ref.struct_size = struct_size
    ..ref.flags = flags
    ..ref.reserved = reserved;
}

typedef AetherEventCallback =
    ffi.Pointer<ffi.NativeFunction<AetherEventCallbackFunction>>;
typedef AetherEventCallbackFunction =
    ffi.Void Function(
      ffi.Uint64 token,
      ffi.Uint64 sequence,
      ffi.Uint32 kind,
      ffi.Int32 status,
      ffi.Uint64 operation_id,
    );
typedef DartAetherEventCallbackFunction =
    void Function(
      int token,
      int sequence,
      int kind,
      int status,
      int operation_id,
    );

enum AetherEventKind {
  AETHER_PROGRESS(1),
  AETHER_TERMINAL(2);

  final int value;
  const AetherEventKind(this.value);

  static AetherEventKind fromValue(int value) => switch (value) {
    1 => AETHER_PROGRESS,
    2 => AETHER_TERMINAL,
    _ => throw ArgumentError('Unknown value for AetherEventKind: $value'),
  };
}

enum AetherPlatform {
  AETHER_WINDOWS(1),
  AETHER_MACOS(2),
  AETHER_IOS(3),
  AETHER_ANDROID(4),
  AETHER_LINUX(5);

  final int value;
  const AetherPlatform(this.value);

  static AetherPlatform fromValue(int value) => switch (value) {
    1 => AETHER_WINDOWS,
    2 => AETHER_MACOS,
    3 => AETHER_IOS,
    4 => AETHER_ANDROID,
    5 => AETHER_LINUX,
    _ => throw ArgumentError('Unknown value for AetherPlatform: $value'),
  };
}

final class AetherStats extends ffi.Struct {
  @ffi.Uint32()
  external int abi_version;

  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint64()
  external int published_sequence;

  @ffi.Uint64()
  external int acknowledged_sequence;

  @ffi.Uint32()
  external int pending_events;

  @ffi.Uint32()
  external int admitted_operations;

  @ffi.Uint32()
  external int live_handles;

  @ffi.Uint32()
  external int live_threads;

  @ffi.Uint64()
  external int worker_thread_id;

  @ffi.Uint64()
  external int dispatcher_thread_id;

  @ffi.Uint32()
  external int stopped;

  @ffi.Uint32()
  external int reserved;

  static ffi.Pointer<AetherStats> $allocate(
    ffi.Allocator $allocator, {
    required int abi_version,
    required int struct_size,
    required int published_sequence,
    required int acknowledged_sequence,
    required int pending_events,
    required int admitted_operations,
    required int live_handles,
    required int live_threads,
    required int worker_thread_id,
    required int dispatcher_thread_id,
    required int stopped,
    required int reserved,
  }) => $allocator<AetherStats>()
    ..ref.abi_version = abi_version
    ..ref.struct_size = struct_size
    ..ref.published_sequence = published_sequence
    ..ref.acknowledged_sequence = acknowledged_sequence
    ..ref.pending_events = pending_events
    ..ref.admitted_operations = admitted_operations
    ..ref.live_handles = live_handles
    ..ref.live_threads = live_threads
    ..ref.worker_thread_id = worker_thread_id
    ..ref.dispatcher_thread_id = dispatcher_thread_id
    ..ref.stopped = stopped
    ..ref.reserved = reserved;
}

enum AetherStatus {
  AETHER_OK(0),
  AETHER_INVALID_ARGUMENT(1),
  AETHER_ABI_MISMATCH(2),
  AETHER_INVALID_HANDLE(3),
  AETHER_ALREADY_DESTROYED(4),
  AETHER_BUSY(5),
  AETHER_STOPPED(6),
  AETHER_NOT_FOUND(7),
  AETHER_ALREADY_COMPLETE(8),
  AETHER_CANCELLED(9),
  AETHER_QUEUE_FULL(10),
  AETHER_TIMEOUT(11),
  AETHER_INTERNAL_ERROR(12),
  AETHER_BUFFER_TOO_SMALL(13),
  AETHER_UNSUPPORTED(14);

  final int value;
  const AetherStatus(this.value);

  static AetherStatus fromValue(int value) => switch (value) {
    0 => AETHER_OK,
    1 => AETHER_INVALID_ARGUMENT,
    2 => AETHER_ABI_MISMATCH,
    3 => AETHER_INVALID_HANDLE,
    4 => AETHER_ALREADY_DESTROYED,
    5 => AETHER_BUSY,
    6 => AETHER_STOPPED,
    7 => AETHER_NOT_FOUND,
    8 => AETHER_ALREADY_COMPLETE,
    9 => AETHER_CANCELLED,
    10 => AETHER_QUEUE_FULL,
    11 => AETHER_TIMEOUT,
    12 => AETHER_INTERNAL_ERROR,
    13 => AETHER_BUFFER_TOO_SMALL,
    14 => AETHER_UNSUPPORTED,
    _ => throw ArgumentError('Unknown value for AetherStatus: $value'),
  };
}
